apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: digisos
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: docker.pkg.github.com/navikt/sosialhjelp-test-proxy/sosialhjelp-test-proxy:{{version}}
  port: 8080
  accessPolicy:
    inbound:
      rules:
        - application: soknad-api
        - application: innsyn-api
        - application: modia-api
    outbound:
      rules:
        - application: veiviser
        - application: soknad
        - application: soknad-api
        - application: innsyn
        - application: innsyn-api
        - application: modia
        - application: modia-api
        - application: mock-alt-api
        - application: fagsystem-mock
      external:
        - host: "appres.nav.no"
        - host: "nav.psplugin.com"
  ingresses:
    - "https://digisos.labs.nais.io/sosialhjelp"
  prometheus:
    enabled: false
    path: /prometheus
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isAlive
    initialDelay: 20
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  webproxy: true
  env:
    - name: PORT
      value: "8080"
