apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-test-proxy
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: docker.pkg.github.com/navikt/sosialhjelp-test-proxy/sosialhjelp-test-proxy:{{version}}
  port: 8080
  accessPolicy:
    outbound:
      external:
        - host: "appres.nav.no"
        - host: "nav.psplugin.com"
      rules: []
  ingresses:
  prometheus:
    enabled: false
    path: /prometheus
  liveness:
    path: /sosialhjelp/internal/isAlive
    initialDelay: 20
  readiness:
    path: /sosialhjelp/internal/isAlive
    initialDelay: 20
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  webproxy: false
  env:
