apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: {{namespace}}
  labels:
    team: teamdigisos
  annotations:
    nais.io/run-as-group: "0"
    nais.io/read-only-file-system: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: {{image}}
  port: 8080
  accessPolicy:
    outbound:
      external:
        - host: "appres.nav.no"
        - host: "nav.psplugin.com"
        - host: "sosialhjelp-veiviser{{domene}}"
        - host: "sosialhjelp-soknad{{domene}}"
        - host: "sosialhjelp-soknad-api{{domene}}"
        - host: "sosialhjelp-innsyn{{domene}}"
        - host: "sosialhjelp-innsyn-api{{domene}}"
        - host: "sosialhjelp-modia{{domene}}"
        - host: "sosialhjelp-modia-api{{domene}}"
        - host: "sosialhjelp-mock-alt{{domene}}"
        - host: "sosialhjelp-mock-alt-api{{domene}}"
        - host: "sosialhjelp-dialog-bruker{{domene}}"
        - host: "sosialhjelp-dialog-veileder{{domene}}"
        - host: "sosialhjelp-dialog-api{{domene}}"
        - host: "sosialhjelp-fagsystem-mock{{domene}}"
    inbound:
      rules:
        - application: sosialhjelp-soknad-api
        - application: sosialhjelp-innsyn-api
        - application: sosialhjelp-modia-api
        - application: sosialhjelp-dialog-api
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  prometheus:
    enabled: false
    path: /prometheus
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isAlive
    initialDelay: 20
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 1m
      memory: 32Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  webproxy: false
  env:
    - name: PORT
      value: "8080"
    - name: DOMENE
      value: {{domene}}
