apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-proxy-dev
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nais.io/run-as-group: "0"
    nais.io/read-only-file-system: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: {{image}}
  port: 8080
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
        - host: sosialhjelp-soknad-dev.intern.dev.nav.no
        - host: sosialhjelp-soknad-api-dev.intern.dev.nav.no
        - host: sosialhjelp-innsyn-dev.intern.dev.nav.no
        - host: sosialhjelp-innsyn-api-dev.intern.dev.nav.no
        - host: sosialhjelp-modia-dev.intern.dev.nav.no
        - host: sosialhjelp-modia-api-dev.intern.dev.nav.no
        - host: sosialhjelp-avtaler-dev.dev.intern.dev.nav.no
        - host: sosialhjelp-avtaler-api-dev.intern.dev.nav.no
      rules:
        - application: sosialhjelp-soknad-dev
        - application: sosialhjelp-soknad-api-dev
        - application: sosialhjelp-innsyn-dev
        - application: sosialhjelp-innsyn-api-dev
        - application: sosialhjelp-modia-dev
        - application: sosialhjelp-modia-api-dev
        - application: sosialhjelp-avtaler-dev
        - application: sosialhjelp-avtaler-api-dev
    inbound:
      rules:
        - application: sosialhjelp-soknad-api-dev
        - application: sosialhjelp-innsyn-api-dev
        - application: sosialhjelp-modia-api-dev
        - application: sosialhjelp-avtaler-api-dev
  ingresses:
    - "https://digisos.intern.dev.nav.no"
  prometheus:
    enabled: false
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isAlive
    initialDelay: 20
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 1m
      memory: 32Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  env:
    - name: PORT
      value: "8080"
    - name: DOMENE_PA_UTSIDEN
      value: ".intern.dev.nav.no"
    - name: DOMENE_PA_INNSIDEN
      value: "-dev.dev.nav.no"
