name: Deploy GCP
on:
  workflow_dispatch:
    inputs:
      config-file-name:
        description: 'Config-fil som skal deployes'
        required: true
        default: 'mock'
        type: choice
        options:
          - 'mock'
          - 'dev'

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@v2
      - name: Sett env variabler
        run: |
          PROJECT_NAME=$(echo ${{ github.repository }} | cut -d/ -f2)
          echo "IMAGE=ghcr.io/${{ github.repository }}/$PROJECT_NAME:${{ steps.artifact-version.outputs.version }}" >> $GITHUB_ENV
      - name: Deploy til GCP
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/${{ github.event.inputs.config-file-name }}.yaml
          CLUSTER: dev-gcp
          REF: ${{ steps.artifact-version.outputs.version }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.IMAGE }}
