name: Deploy GCP
on:
  workflow_dispatch:
    inputs:
      config-file-name:
        description: 'Config-fil som skal deployes'
        required: true
        default: 'dev-gcp'
        type: choice
        options:
          - 'dev-gcp'
          - 'dev-gcp-mock'
          - 'labs-gcp'
      cluster:
        description: 'Cluster å deploye til'
        required: true
        default: 'dev-gcp'
        type: choice
        options:
          - 'dev-gcp'
          - 'labs-gcp'

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master
      - name: Sett env variabler
        run: |
          PROJECT_NAME=$(echo ${{ github.repository }} | cut -d/ -f2)
          echo "IMAGE=ghcr.io/${{ github.repository }}/$PROJECT_NAME:${{ steps.artifact-version.outputs.version }}" >> $GITHUB_ENV
          echo "CLUSTER_NAME=${{ github.event.inputs.cluster }}" >> $GITHUB_ENV
          echo "CONFIG_FILE=${{ github.event.inputs.config-file-name }}" >> $GITHUB_ENV
      - name: Deploy til GCP
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais.yaml
          CLUSTER: ${{ env.CLUSTER_NAME }}
          VARS: nais/${{ env.CONFIG_FILE }}.json
          REF: ${{ steps.artifact-version.outputs.version }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.IMAGE }}
